### ISSUE TITLE
Design Issue: OpenNebula Object IDs

### ISSUE THREAD

**Issue by rvalle** [privazio/ansible#4]
The way in which OpenNebula works follows this pattern.

- API is used to allocate a resorce.
- an ID is generated  by the system
- The ID is used to update/modify the resource.

At the time of writing the playbooks / inventories IDs are not known. Anyway, IDs are bound to change if the environment is trashed and re-created. 

I don't think it is possible to use the IDs as parameter to modules, even thou it seems the most natural approach.

**Comment by marcindulak** [comment]
I think the (optional) IDs as module parameters is what we need https://blog.scottlowe.org/2016/10/23/managing-aws-infrastructure-ansible/. This is what aws ansible modules are doing with help of the dynamic inventory. We are limited to VMs only.
For example http://docs.ansible.com/ansible/devel/modules/ec2_module.html#ec2
```
- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
```

http://docs.ansible.com/ansible/devel/modules/ec2_vpc_module.html#ec2-vpc
```
# Removal of a VPC by id
    - ec2_vpc:
        state: absent
        vpc_id: vpc-aaaaaaa
        region: us-west-2
```

Using the opennebula.py dynamic inventory this can be done with the following `instance.yml` playbook:
```
- hosts: ansible_host
  
  tasks:

  - name: "destroy {{ inventory_hostname }} with IP {{ ansible_host }} by ID"
    debug: var=hostvars['{{ inventory_hostname }}']['ID']
```

```
ansible-playbook -i opennebula.py instance.yml

PLAY [ansible_host] *************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [testvm-0]

TASK [destroy testvm-0 with IP 192.168.10.100 by ID] ****************************************************************************************************************************
ok: [testvm-0] => {
    "hostvars['testvm-0']['ID']": "0"
}

PLAY RECAP **********************************************************************************************************************************************************************
testvm-0                   : ok=2    changed=0    unreachable=0    failed=0   
```
